apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: clientgodemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientgodemo
  template:
    metadata:
      labels:
        app: clientgodemo
    spec:
      containers:
      - image: registry.local:5000/clientgodemo:v3
        imagePullPolicy: IfNotPresent
        name: clientgodemo